import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const plantCatalog = [
  {
    commonName: "Monstera",
    scientificName: "Monstera deliciosa",
    family: "Aracées",
    emoji: "🌿",
    category: "INDOOR",
    descriptionShort: "La plante tropicale aux grandes feuilles perforées, idéale pour les intérieurs lumineux.",
    sunExposure: "PARTIAL",
    wateringFreqDays: 10,
    wateringDifficulty: "EASY",
    minTempCelsius: 15,
    indoor: true,
    outdoor: false,
    toxic: true,
    tags: JSON.stringify(["tropical", "tendance", "grande feuille"]),
  },
  {
    commonName: "Ficus",
    scientificName: "Ficus benjamina",
    family: "Moracées",
    emoji: "🌳",
    category: "INDOOR",
    descriptionShort: "Arbre d'intérieur classique, sensible aux déplacements.",
    sunExposure: "PARTIAL",
    wateringFreqDays: 7,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: 15,
    indoor: true,
    outdoor: false,
    toxic: true,
    tags: JSON.stringify(["arbre intérieur", "classique"]),
  },
  {
    commonName: "Pothos",
    scientificName: "Epipremnum aureum",
    family: "Aracées",
    emoji: "🌿",
    category: "INDOOR",
    descriptionShort: "Plante retombante ultra-résistante, parfaite pour les débutants.",
    sunExposure: "SHADE",
    wateringFreqDays: 14,
    wateringDifficulty: "EASY",
    minTempCelsius: 12,
    indoor: true,
    outdoor: false,
    toxic: true,
    tags: JSON.stringify(["débutant", "retombante", "facile"]),
  },
  {
    commonName: "Cactus boule",
    scientificName: "Echinopsis",
    family: "Cactacées",
    emoji: "🌵",
    category: "SUCCULENTS",
    descriptionShort: "Cactus sphérique très résistant, arrosage rare.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 21,
    wateringDifficulty: "EASY",
    minTempCelsius: 5,
    indoor: true,
    outdoor: true,
    tags: JSON.stringify(["cactée", "succulente", "xérophyte"]),
  },
  {
    commonName: "Orchidée Phalaenopsis",
    scientificName: "Phalaenopsis",
    family: "Orchidacées",
    emoji: "🌸",
    category: "INDOOR",
    descriptionShort: "Orchidée de maison aux longues tiges fleuries, floraison majestueuse.",
    sunExposure: "PARTIAL",
    wateringFreqDays: 10,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: 16,
    indoor: true,
    outdoor: false,
    tags: JSON.stringify(["fleur", "élégante", "longue floraison"]),
  },
  {
    commonName: "Tomate",
    scientificName: "Solanum lycopersicum",
    family: "Solanacées",
    emoji: "🍅",
    category: "VEGETABLE",
    descriptionShort: "Le légume star du potager, nombreuses variétés disponibles.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 2,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: 15,
    indoor: false,
    outdoor: true,
    edible: true,
    fertilizerMonths: JSON.stringify([5, 6, 7, 8]),
    tags: JSON.stringify(["légume", "été", "potager"]),
  },
  {
    commonName: "Courgette",
    scientificName: "Cucurbita pepo",
    family: "Cucurbitacées",
    emoji: "🥒",
    category: "VEGETABLE",
    descriptionShort: "Légume prolixe et facile, idéal pour les débutants au potager.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 3,
    wateringDifficulty: "EASY",
    minTempCelsius: 15,
    indoor: false,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["légume", "facile", "été", "productif"]),
  },
  {
    commonName: "Laitue",
    scientificName: "Lactuca sativa",
    family: "Astéracées",
    emoji: "🥬",
    category: "VEGETABLE",
    descriptionShort: "Salade rapide à pousser, idéale pour une première récolte.",
    sunExposure: "PARTIAL",
    wateringFreqDays: 2,
    wateringDifficulty: "EASY",
    minTempCelsius: 5,
    indoor: false,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["salade", "printemps", "automne", "rapide"]),
  },
  {
    commonName: "Carotte",
    scientificName: "Daucus carota",
    family: "Apiacées",
    emoji: "🥕",
    category: "VEGETABLE",
    descriptionShort: "Légume racine classique, sol meuble et profond requis.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 4,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: 7,
    indoor: false,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["légume", "racine", "printemps"]),
  },
  {
    commonName: "Poivron",
    scientificName: "Capsicum annuum",
    family: "Solanacées",
    emoji: "🌶️",
    category: "VEGETABLE",
    descriptionShort: "Légume du soleil, chaleur et arrosage régulier.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 2,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: 18,
    indoor: false,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["légume", "été", "chaleur"]),
  },
  {
    commonName: "Basilic",
    scientificName: "Ocimum basilicum",
    family: "Lamiacées",
    emoji: "🌿",
    category: "HERBS",
    descriptionShort: "L'aromate incontournable, fragile au froid et à l'excès d'eau.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 2,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: 15,
    indoor: true,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["aromatique", "cuisine", "été"]),
  },
  {
    commonName: "Menthe",
    scientificName: "Mentha",
    family: "Lamiacées",
    emoji: "🌿",
    category: "HERBS",
    descriptionShort: "Aromatique envahissante à planter en pot. Robuste et parfumée.",
    sunExposure: "PARTIAL",
    wateringFreqDays: 3,
    wateringDifficulty: "EASY",
    minTempCelsius: -10,
    indoor: true,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["aromatique", "pot", "robuste"]),
  },
  {
    commonName: "Romarin",
    scientificName: "Salvia rosmarinus",
    family: "Lamiacées",
    emoji: "🌿",
    category: "HERBS",
    descriptionShort: "Aromatique méditerranéen très résistant à la sécheresse.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 14,
    wateringDifficulty: "EASY",
    minTempCelsius: -10,
    indoor: false,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["aromatique", "méditerranéen", "sec"]),
  },
  {
    commonName: "Rosier",
    scientificName: "Rosa",
    family: "Rosacées",
    emoji: "🌹",
    category: "FLOWERS",
    descriptionShort: "La reine des jardins, nombreuses variétés, floraison estivale.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 5,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: -15,
    indoor: false,
    outdoor: true,
    fertilizerMonths: JSON.stringify([3, 4, 5, 6]),
    tags: JSON.stringify(["fleur", "classique", "parfumé"]),
  },
  {
    commonName: "Lavande",
    scientificName: "Lavandula angustifolia",
    family: "Lamiacées",
    emoji: "💜",
    category: "FLOWERS",
    descriptionShort: "Incontournable du jardin méditerranéen, floraison violette parfumée.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 14,
    wateringDifficulty: "EASY",
    minTempCelsius: -20,
    indoor: false,
    outdoor: true,
    edible: true,
    tags: JSON.stringify(["fleur", "méditerranéen", "parfumé", "mellifère"]),
  },
  {
    commonName: "Géranium",
    scientificName: "Pelargonium",
    family: "Géraniacées",
    emoji: "🌸",
    category: "FLOWERS",
    descriptionShort: "Fleur de balcon par excellence, colorée et résistante à la chaleur.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 3,
    wateringDifficulty: "EASY",
    minTempCelsius: 5,
    indoor: false,
    outdoor: true,
    tags: JSON.stringify(["balcon", "été", "coloré"]),
  },
  {
    commonName: "Pommier",
    scientificName: "Malus domestica",
    family: "Rosacées",
    emoji: "🍎",
    category: "TREES_SHRUBS",
    descriptionShort: "Arbre fruitier classique, nombreuses variétés selon la région.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 7,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: -25,
    indoor: false,
    outdoor: true,
    edible: true,
    fertilizerMonths: JSON.stringify([3, 4]),
    tags: JSON.stringify(["fruitier", "arbres", "automne"]),
  },
  {
    commonName: "Hortensia",
    scientificName: "Hydrangea macrophylla",
    family: "Hydrangéacées",
    emoji: "💐",
    category: "FLOWERS",
    descriptionShort: "Grand arbuste à fleurs en boules, besoin en eau élevé.",
    sunExposure: "PARTIAL",
    wateringFreqDays: 3,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: -15,
    indoor: false,
    outdoor: true,
    tags: JSON.stringify(["arbuste", "ombre", "fleur", "estival"]),
  },
  {
    commonName: "Glycine",
    scientificName: "Wisteria sinensis",
    family: "Fabacées",
    emoji: "🌸",
    category: "CLIMBING",
    descriptionShort: "Grimpante majestueuse aux grappes fleuries au printemps.",
    sunExposure: "FULL_SUN",
    wateringFreqDays: 7,
    wateringDifficulty: "MEDIUM",
    minTempCelsius: -20,
    indoor: false,
    outdoor: true,
    toxic: true,
    tags: JSON.stringify(["grimpante", "printemps", "parfumé", "pergola"]),
  },
  {
    commonName: "Lierre",
    scientificName: "Hedera helix",
    family: "Araliacées",
    emoji: "🍃",
    category: "CLIMBING",
    descriptionShort: "Grimpante persistante ultra-robuste, couvre-sol ou murale.",
    sunExposure: "SHADE",
    wateringFreqDays: 14,
    wateringDifficulty: "EASY",
    minTempCelsius: -25,
    indoor: true,
    outdoor: true,
    toxic: true,
    tags: JSON.stringify(["grimpante", "persistante", "couvre-sol"]),
  },
]

async function main() {
  console.log('🌱 Seeding plant catalog...')
  for (const plant of plantCatalog) {
    await prisma.plantCatalog.upsert({
      where: { scientificName: plant.scientificName },
      update: plant,
      create: plant,
    })
  }
  console.log(`✅ ${plantCatalog.length} plants seeded.`)
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect())
