// growi-frontend/lib/mock-weather.ts
// Mock weather data for Paris (lat: 48.8566, lon: 2.3522) — used in development
import type { WeatherData } from '@/types/weather'

export const mockWeatherData: WeatherData = {
  locationName: 'Paris, Île-de-France',
  elevation: 35,
  fetchedAt: new Date().toISOString(),
  current: {
    temperature: 18,
    apparentTemperature: 16,
    humidity: 65,
    precipitation: 0,
    weatherCode: 2,
    windSpeed: 12,
    windDirection: 245,
    time: new Date().toISOString(),
  },
  forecast: [
    {
      date: new Date(Date.now() + 0 * 86400000).toISOString().split('T')[0],
      weatherCode: 2,
      tempMax: 19,
      tempMin: 10,
      precipitationSum: 0,
      precipitationProbability: 10,
      sunrise: '06:45',
      sunset: '20:15',
    },
    {
      date: new Date(Date.now() + 1 * 86400000).toISOString().split('T')[0],
      weatherCode: 0,
      tempMax: 22,
      tempMin: 12,
      precipitationSum: 0,
      precipitationProbability: 5,
      sunrise: '06:43',
      sunset: '20:17',
    },
    {
      date: new Date(Date.now() + 2 * 86400000).toISOString().split('T')[0],
      weatherCode: 1,
      tempMax: 20,
      tempMin: 11,
      precipitationSum: 0,
      precipitationProbability: 15,
      sunrise: '06:41',
      sunset: '20:18',
    },
    {
      date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
      weatherCode: 61,
      tempMax: 14,
      tempMin: 9,
      precipitationSum: 8.2,
      precipitationProbability: 80,
      sunrise: '06:39',
      sunset: '20:20',
    },
    {
      date: new Date(Date.now() + 4 * 86400000).toISOString().split('T')[0],
      weatherCode: 63,
      tempMax: 12,
      tempMin: 7,
      precipitationSum: 14.5,
      precipitationProbability: 90,
      sunrise: '06:37',
      sunset: '20:22',
    },
    {
      date: new Date(Date.now() + 5 * 86400000).toISOString().split('T')[0],
      weatherCode: 3,
      tempMax: 15,
      tempMin: 8,
      precipitationSum: 1.2,
      precipitationProbability: 30,
      sunrise: '06:35',
      sunset: '20:23',
    },
    {
      date: new Date(Date.now() + 6 * 86400000).toISOString().split('T')[0],
      weatherCode: 0,
      tempMax: 21,
      tempMin: 11,
      precipitationSum: 0,
      precipitationProbability: 5,
      sunrise: '06:33',
      sunset: '20:25',
    },
  ],
}
